### PR TITLE
Use `filter_stream` instead of `filter`

### PR DESCRIPTION
**Pull request by okkez**
This can improve performance.

### CODE REVIEW

**Comment by y-ken** [comment]
Thank you.

**Comment by okkez** [comment]
Hmm, I misunderstood https://github.com/y-ken/fluent-plugin-geoip/pull/24#discussion_r36718328

**Comment by y-ken** [comment]
It seems useful for filter not only emit.

**Comment by okkez** [comment]
I think that this PR needs benchmark.

**Comment by y-ken** [comment]
I agree to need benchmarking. Would you please measure the improbements?

**Comment by okkez** [comment]
@y-ken OK. I will do it in next week.

**Comment by okkez** [comment]
I added following patch to fluentd.

```diff
diff --git a/lib/fluent/event_router.rb b/lib/fluent/event_router.rb
index 339e406..3f225e0 100644
--- a/lib/fluent/event_router.rb
+++ b/lib/fluent/event_router.rb
@@ -146,9 +146,14 @@ module Fluent
 
       def emit(tag, es, chain)
         processed = es
+        start = Time.now.to_f
         @filters.each { |filter|
           processed = filter.filter_stream(tag, processed)
         }
+        elapsed = Time.now.to_f - start
+        File.open("/tmp/log.txt", "a") do |file|
+          file.puts(elapsed)
+        end
         @output.emit(tag, processed, chain)
       end
     end
```

Process 120k records via in_tail plugin using following config.

```aconf
<source>
  @type tail
  tag raw.dummy
  path dummy.log
  read_from_head true
  format /^(?<id>id:\d+)\t(?<host>host:.*)$/
</source>

<filter raw.**>
  @type geoip
  geoip_lookup_key  host
  <record>
    city            ${city["host"]}
    latitude        ${latitude["host"]}
    longitude       ${longitude["host"]}
    country_code3   ${country_code3["host"]}
    country         ${country_code["host"]}
    country_name    ${country_name["host"]}
    dma             ${dma_code["host"]}
    area            ${area_code["host"]}
    region          ${region["host"]}
  </record>
  flush_interval    1s
</filter> 

<match raw.**>
  @type null
</match>
```

Process 120k records in:

* filter: 3.535801410675049
* filter_emit: 3.169358491897583

`filter_emit` is about 10% faster.

**Comment by okkez** [comment]
We can reduce method dispatch for each `filter_stream` in `fluent/filter.rb` when we use `filter_stream` version.

**Comment by y-ken** [comment]
Thank you!

**Comment by okkez** [comment]
Yes!

**Comment by y-ken** [comment]
Got 10% faster :beers:

**Pull request merged**
