### PR TITLE
Add skip_adding_null_record option

### PR DESCRIPTION
**Pull request by y-ken**
Hi all,

On the case of getting nothing of GeoIP info (such as local IP),
it will output the original record without changing anything.

Original Issue: https://github.com/y-ken/fluent-plugin-geoip/issues/18

### CODE REVIEW

**Comment by Seraf** [comment]
Hello,

Thanks for this patch. I would like to test it but not sure about how to install this version with tdagent2 ?

**Comment by y-ken** [comment]
Hi @Seraf 

Thank you for your reply.
I'll publish this gem as pre-release version.
Would you please install that and check the behavior after gem has released?

**Comment by Seraf** [comment]
Yes, let just me know when it will be done and I will try it :)

Thanks

**Comment by y-ken** [comment]
Released now.
https://rubygems.org/gems/fluent-plugin-geoip

On td-agent2, you can install pre-release version with following commands.

```
$ sudo /usr/sbin/td-agent-gem install fluent-plugin-geoip --pre
```

ref. http://guides.rubygems.org/patterns/#prerelease-gems

**Comment by Seraf** [comment]
Seems to work great :) Thanks !

**Comment by y-ken** [comment]
Thank you for quick reply! I've released v0.5.0 now.
https://rubygems.org/gems/fluent-plugin-geoip

**Comment by Seraf** [comment]
You're welcome :) Thanks to you for this patch, ElasticSearch logs are very happy now !

**Pull request merged**
