### PR TITLE
Add test for geoip2_c and geoip2_compat

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
See also #39 #42

**Comment by okkez** [comment]
I've added test using docker-compose on TravisCI.
But I have not added matrix using old Ruby versions such as 1.9.3 and 2.0.0 because these versions have reached EOL.
And I ignored Fluentd v0.10.x because v0.10.x have reached EOL.

Is this ok?

**Comment by y-ken** [comment]
Thank you very much.
YES. I agree to drop ruby < 2.1 and fluentd < 0.12.

**Comment by okkez** [comment]
Thanks.
I will create another PR to drop old Fluentd < 0.12.
Maybe after merge this PR.

**Comment by okkez** [comment]
@y-ken I've dropped old Fluentd support in this PR.

**Comment by okkez** [comment]
@y-ken Do you have any concern?

**Comment by y-ken** [comment]
Great. Thank you.

**Comment by okkez** [comment]
Wow, thanks!

**Pull request merged**
