### PR TITLE
Use `emit_stream` instead of `emit`

### PR DESCRIPTION
**Pull request by okkez**
This is for performance.
See https://github.com/y-ken/fluent-plugin-geoip/pull/24#discussion_r36718328

### CODE REVIEW

**Comment by y-ken** [comment]
How about the performance improvements from now?

**Comment by okkez** [comment]
I write a patch to benchmark. (I'm not sure that this is suitable for benchmark.)
Configuration is same as https://github.com/y-ken/fluent-plugin-geoip/pull/30#issuecomment-177761222

```diff
diff --git a/lib/fluent/plugin/out_geoip.rb b/lib/fluent/plugin/out_geoip.rb
index aee5114..500b6b6 100644
--- a/lib/fluent/plugin/out_geoip.rb
+++ b/lib/fluent/plugin/out_geoip.rb
@@ -55,8 +55,20 @@ class Fluent::GeoipOutput < Fluent::BufferedOutput
   end
 
   def write(chunk)
-    chunk.msgpack_each do |tag, time, record|
-      router.emit(tag, time, @geoip.add_geoip_field(record))
+    start = Time.now.to_f
+    # chunk.msgpack_each do |tag, time, record|
+    #   router.emit(tag, time, @geoip.add_geoip_field(record))
+    # end
+    es = Fluent::MultiEventStream.new
+    tag = ""
+    chunk.msgpack_each do |_tag, time, record|
+      tag = _tag
+      es.add(time, @geoip.add_geoip_field(record))
+    end
+    router.emit_stream(tag, es)
+    elapsed = Time.now.to_f - start
+    File.open("/tmp/output-stream.log", "a+") do |file|
+      file.puts(elapsed)
     end
   end
 end
```

As a result:

* `router.emit` : 3.576
* `router.emit_stream`: 3.46

`router.emit_stream` is faster than `route.emit` in about 0.1s.

**Comment by y-ken** [comment]
OK! Thank you very much.

**Comment by okkez** [comment]
Thank you for merging :bow:

**Pull request merged**
